name: nameof_annotation
description: Annotations for nameof package, that is Generator for  Dart class member's names, such as fields, properties, methods, constructors 
version: 0.2.0
homepage: https://github.com/flankb/nameof

environment:
  sdk: ^3.0.0

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
