name: nameof_annotation
description: Annotations for nameof package
version: 0.1.0
homepage: https://github.com/flankb/nameof

environment:
  sdk: '>=2.16.1 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
