targets:
  $default:
    builders:
      nameof:
        enabled: true

builders:
  freezed:
    import: "package:nameof/builder.dart"
    builder_factories: ["nameof"]
    build_extensions: { ".dart": [".nameof.dart"] }
    auto_apply: dependents
    build_to: source