name: nameof
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.16.1 <3.0.0'


dependencies:
  build: 
  source_gen:
  nameof_annotation: 
    path: ../nameof_annotation/

dev_dependencies:
  build_runner:
  lints: ^1.0.0
  test: ^1.16.0
