name: nameof
description: Generator for  Dart class member's names, such as fields, properties, methods, constructors 
version: 0.2.3
homepage: https://github.com/flankb/nameof

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  analyzer: ">=7.5.9 <9.0.0"
  build: ">=3.0.0 <5.0.0"
  source_gen: ">=3.0.0 <5.0.0"
  build_config: ^1.2.0
  nameof_annotation:
    path: ../nameof_annotation/


dev_dependencies:
  build_runner: ^2.8.0
  build_test: ^3.4.0
  source_gen_test: ^1.3.2
  lints: ^6.0.0
  test: ^1.26.3
