name: nameof
description: Generator for  Dart class member's names, such as fields, properties, methods, constructors 
version: 0.1.2
homepage: https://github.com/flankb/nameof

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  analyzer: '>=2.0.0 <5.0.0'
  build: ^2.0.0 
  source_gen: ^1.2.0
  build_config: ^1.0.0
  nameof_annotation: ^0.1.0

dev_dependencies:
  build_runner: ^2.1.11
  build_test: ^2.1.5
  source_gen_test: ^1.0.2
  lints: ^1.0.0
  test: ^1.16.0
