name: example
description: Example for nameof package
version: 1.1.0
# homepage: https://www.example.com

environment:
  sdk: ^3.8.0


dependencies:
  nameof_annotation:
    path: ../../nameof_annotation/

dev_dependencies:
  lints: ^6.1.0
  build_runner:
  # nameof: ^0.2.0
  nameof:
    path: ../
